services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Typoheads\Formhandler\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Utility/*'

  Typoheads\Formhandler\Utility\TcaSiteLanguagesProcFunc:
    public: true
