services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Typoheads\Formhandler\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Utility/*'
      - '../Classes/Ajax/*'
      - '../Classes/Http/*'
